### ISSUE TITLE
Review: UnderParticipationForm.jsx and EditTeamWidget.jsx

### ISSUE THREAD

**Issue by jaydent22** [moores-minions/HACC-Hui#200]
## Overview

The focus for this code review will be centered around UnderParticipationForm.jsx and EditTeamWidget.jsx

Please pay attention to:
* Javascript issues
* React components
* Naming Conventions

## Review Branch

review-009

## Files to review

* [UnderParticipationForm.jsx](https://github.com/moores-minions/HACC-Hui/blob/main/app/imports/ui/pages/participant/UnderParticipationForm.jsx)
* [EditTeamWidget.jsx](https://github.com/moores-minions/HACC-Hui/blob/main/app/imports/ui/components/participant/EditTeamWidget.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

([Combined checklist for ease](https://github.com/moores-minions/HACC-Hui/blob/main/checklists/combined-checklist.md))

## Due date

11/6/23

**Comment by jaydent22** [comment]
## UnderParticipationForm.jsx

- L25 incorrect component comment
- Remove calls to console (use sweetalert instead of console.error)
- Arrow function, update state from class to arrow function version

## EditTeamWidget.jsx

- Arrow function, arrow function state instead of class state
- useTracker instead of withTracker
- allSkills/Challenges/etc. props may be unnecessary; can use them as variables in arrow function instead
- L190 use existing button styles for consistency (e.g., default style, success variant, danger variant)
- L195 ErrorsField before SubmitField

**Comment by chenglisa** [comment]
### UnderParticipationForm.jsx 

- L28 convert class to arrow function 
- Change the console.error to sweetalert (swal) 
- L25 change the comment, currently says "landing page" 

### EditTeamWidget.jsx
- Remove the withRouter and withTracker -> useTracker
- Convert to arrow function
- Remove the calls to console.log

**Comment by caciems** [comment]
### UnderParticipationForm.jsx
- Arrow functions 

### EditTeamWidget.jsx
- L155 Move style to style.css 
- Change to arrow functions 
- Change from withTracker to useTracker
